# Generated by Django 3.0.8 on 2020-08-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('DEL', 'DELUXE'), ('YAC', 'AC'), ('NAC', 'NON-AC')], max_length=3)),
                ('beds', models.IntegerField()),
            ],
        ),
    ]
